server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # Encaminha Authorization para os serviços downstream (por padrão pode ser tratado como sensível)
      proxy:
        sensitive: []  # nenhum header sensível; Authorization é repassado
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/auth/**

            - id: flag-service
              uri: http://flag-service:8082
              predicates:
                - Path=/flags/**

            - id: evaluation-service
              uri: http://evaluation-service:8083
              predicates:
                - Path=/evaluate/**
