server:
  port: 8083

spring:
  application:
    name: evaluation-service

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}

flag-service-url: ${FLAG_SERVICE_URL:http://localhost:8082}
